### ISSUE TITLE
ENH: Format sensor data after it's been extracted

### ISSUE THREAD

**Issue by csmcallister** [GSA/wb2#1]
We have a script that extracts all of the data from the [csvs](https://drive.google.com/drive/u/0/folders/1Ah7MOw99aKeQazV5bOAxG8r0zR4jHI5r), but now we need to transform it.

## Expected Behavior
The data frame is transformed from wide to long, with `modality`, `unit`, and `value` columns replacing the current sensor value columns:
```python
cols_to_melt = ['CO2__ppm', 'CO__ppm', 'Humidity__pct', 'PN1Plus__counts_per_L', 
'Pressure__mbar', 'Temperature__deg_C', 'humidity_2_rel_true_pct_avg', 'light_lux', 
'room_type', 'sound_dba_avg', 'temperature_2_celsius_avg', 'vibration_ms2_avg']
```
A modality is something like `CO2` whereas the unit is something like `pct` or `counts_per_L`.

The final data frame should look something like this:

|Datetime|Building|Floor|Room|Room Type|Modality|Unit|Value|
|--- |--- |--- |--- |--- |--- |--- |--- |
|2017-02-24 00:00:00|1800 f|2|2240|None|CO|ppm|0.827||
|2017-02-24 00:00:00|1800 f|2|2240|None|CO|ppm|0.827||

## Current Behavior
Data is long: 😢 
<img width="1028" alt="screen shot 2019-02-07 at 2 36 19 pm" src="https://user-images.githubusercontent.com/33464354/52437791-c86d6280-2ae5-11e9-8e30-ab941f145801.png">

**Comment by kstreepy** [comment]
New functions added to reformat data as requested. Please review and let me know if any adjustments are needed.

**Comment by csmcallister** [comment]
@kstreepy good work 🍻 
I made a few edits, mostly so that we're not relying on global variables (like `final_df`) and so that the unnamed column is dropped before the reshape.
